import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { A11yAuditor, ReportGenerator, toAuditConfig } from '@a11y-ai/core';
import type { AuditResult } from '@a11y-ai/core';

import { readInputsFromEnv } from './lib.js';

type ProviderName = 'openai' | 'anthropic' | 'ollama' | 'custom' | 'mock';

async function run(): Promise<void> {
  const inputs = readInputsFromEnv(process.env);

  if (!inputs.url && !inputs.htmlPath) {
    failHard('You must provide either "url" or "html-path" input.');
    return;
  }

  const config = toAuditConfig({
    preset: inputs.preset,
    provider: {
      provider: toProviderName(inputs.provider),
      apiKey: inputs.apiKey || undefined,
    },
  });

  console.log(`🔍 Starting a11y-ai audit...`);
  console.log(`   Target: ${inputs.url || inputs.htmlPath}`);
  console.log(`   Preset: ${inputs.preset}`);
  console.log(`   Threshold: ${inputs.threshold}`);

  const auditor = new A11yAuditor(config);
  let result: AuditResult;

  try {
    if (inputs.htmlPath) {
      const html = readFileSync(resolve(inputs.htmlPath), 'utf8');
      result = await auditor.auditHTML(html);
    } else {
      result = await auditor.auditURL(inputs.url!);
    }
  } catch (error) {
    failHard(`Audit failed: ${error instanceof Error ? error.message : String(error)}`);
    return;
  }

  const reporter = new ReportGenerator();
  const htmlReport = reporter.generateHTML(result);
  const mdReport = reporter.generateMarkdown(result);
  const jsonReport = reporter.generateJSON(result);
  const sarifReport = reporter.generateSARIF(result);

  const htmlPath = resolve(process.cwd(), 'a11y-ai-report.html');
  const mdPath = resolve(process.cwd(), 'a11y-ai-report.md');
  const jsonPath = resolve(process.cwd(), 'a11y-ai-report.json');
  const sarifPath = resolve(process.cwd(), 'a11y-ai-report.sarif.json');

  writeFileSync(htmlPath, htmlReport, 'utf8');
  writeFileSync(mdPath, mdReport, 'utf8');
  writeFileSync(jsonPath, jsonReport, 'utf8');
  writeFileSync(sarifPath, sarifReport, 'utf8');

  const score = result.summary.score;
  const grade = result.summary.grade;
  const violationCount = result.mergedViolations.length;

  const thresholdPassed = score >= inputs.threshold;
  const criticalViolations = inputs.failOnViolations
    ? result.mergedViolations.filter((v) => v.severity === 'critical')
    : [];
  const criticalPassed = criticalViolations.length === 0;

  const passed = thresholdPassed && criticalPassed;
  const failReason = !thresholdPassed
    ? `Score ${score} is below threshold ${inputs.threshold}.`
    : !criticalPassed
      ? `Critical violations found: ${criticalViolations.length}.`
      : '';

  setOutput('score', String(score));
  setOutput('grade', grade);
  setOutput('violations', String(violationCount));
  setOutput('report-path', htmlPath);
  setOutput('report-md-path', mdPath);
  setOutput('report-json-path', jsonPath);
  setOutput('report-sarif-path', sarifPath);
  setOutput('passed', passed ? 'true' : 'false');
  setOutput('fail-reason', failReason);

  const emoji = passed ? '✅' : '❌';
  console.log(`\n${emoji} Audit complete!`);
  console.log(`   Score: ${score} (${grade})`);
  console.log(`   Violations: ${violationCount}`);
  console.log(`   Passed: ${passed}`);
  if (failReason) console.log(`   Reason: ${failReason}`);

  writeSummary(result, passed);

  await postPrComment(result);
}

function setOutput(name: string, value: string): void {
  const outPath = process.env.GITHUB_OUTPUT;
  if (!outPath) {
    console.log(`::set-output name=${name}::${escapeOutput(value)}`);
    return;
  }
  writeFileSync(outPath, `${name}=${escapeOutput(value)}\n`, { encoding: 'utf8', flag: 'a' });
}

function escapeOutput(value: string): string {
  return value.replace(/\r?\n/g, ' ');
}

function writeSummary(result: AuditResult, passed: boolean): void {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (!summaryPath) return;

  const { score, grade, bySeverity, totalViolations } = result.summary;
  const emoji = passed ? '✅' : '❌';

  const summary = `## ${emoji} a11y-ai Accessibility Report

| Score | Grade | Critical | Serious | Moderate | Minor | Total |
|:-----:|:-----:|:--------:|:-------:|:--------:|:-----:|:-----:|
| **${score}** | **${grade}** | ${bySeverity.critical} | ${bySeverity.serious} | ${bySeverity.moderate} | ${bySeverity.minor} | ${totalViolations} |

${
  result.mergedViolations.length > 0
    ? `### Top Issues

${result.mergedViolations
  .slice(0, 5)
  .map((v) => {
    const sevEmoji = v.severity === 'critical' ? '🔴' : v.severity === 'serious' ? '🟠' : '🔵';
    return `- ${sevEmoji} **${v.severity}**: ${v.message}`;
  })
  .join('\n')}`
    : '### No violations found! 🎉'
}

> Generated by [a11y-ai](https://github.com/vudayagirivaibhav/a11y-ai)
`;

  writeFileSync(summaryPath, summary, { encoding: 'utf8', flag: 'a' });
}

async function postPrComment(result: AuditResult): Promise<void> {
  const githubToken = process.env.GITHUB_TOKEN;
  const eventName = process.env.GITHUB_EVENT_NAME;
  const repo = process.env.GITHUB_REPOSITORY;
  const eventPath = process.env.GITHUB_EVENT_PATH;

  if (!githubToken || !repo || !eventPath) {
    console.log('ℹ️  Skipping PR comment (missing GITHUB_TOKEN or not in GitHub Actions context)');
    return;
  }

  if (eventName !== 'pull_request' && eventName !== 'pull_request_target') {
    console.log('ℹ️  Skipping PR comment (not a pull request event)');
    return;
  }

  let prNumber: number | undefined;
  try {
    const event = JSON.parse(readFileSync(eventPath, 'utf8'));
    prNumber = event.pull_request?.number;
  } catch {
    console.log('ℹ️  Skipping PR comment (could not read event file)');
    return;
  }

  if (!prNumber) {
    console.log('ℹ️  Skipping PR comment (no PR number found)');
    return;
  }

  const body = formatPrComment(result);
  const [owner, repoName] = repo.split('/');

  console.log(`📝 Posting comment to PR #${prNumber}...`);

  try {
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/issues/${prNumber}/comments`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${githubToken}`,
          'Content-Type': 'application/json',
          Accept: 'application/vnd.github.v3+json',
          'User-Agent': 'a11y-ai-github-action',
        },
        body: JSON.stringify({ body }),
      },
    );

    if (response.ok) {
      console.log('✅ PR comment posted successfully');
    } else {
      const text = await response.text();
      console.log(`⚠️  Failed to post PR comment: ${response.status} ${text}`);
    }
  } catch (error) {
    console.log(`⚠️  Failed to post PR comment: ${error instanceof Error ? error.message : error}`);
  }
}

function formatPrComment(result: AuditResult): string {
  const { score, grade, bySeverity, totalViolations } = result.summary;
  const emoji = score >= 80 ? '✅' : score >= 70 ? '⚠️' : '❌';

  const top5 =
    result.mergedViolations.length > 0
      ? result.mergedViolations
          .slice(0, 5)
          .map((v) => {
            const sevEmoji =
              v.severity === 'critical' ? '🔴' : v.severity === 'serious' ? '🟠' : '🔵';
            return `${sevEmoji} **${v.severity.toUpperCase()}** — ${v.message} (\`${truncate(v.selector, 50)}\`)`;
          })
          .join('\n')
      : '_No violations found._';

  const allViolations =
    result.mergedViolations.length > 0
      ? result.mergedViolations
          .map(
            (v) =>
              `| ${v.severity} | ${v.category ?? '-'} | \`${truncate(v.selector, 40)}\` | ${truncate(v.message, 60)} |`,
          )
          .join('\n')
      : '| — | — | — | No violations |';

  return `## ${emoji} a11y-ai Accessibility Report

| Score | Grade | Critical | Serious | Moderate | Minor | Total |
|:-----:|:-----:|:--------:|:-------:|:--------:|:-----:|:-----:|
| **${score}** | **${grade}** | ${bySeverity.critical} | ${bySeverity.serious} | ${bySeverity.moderate} | ${bySeverity.minor} | ${totalViolations} |

### Top Issues
${top5}

<details>
<summary>All violations (${totalViolations})</summary>

| Severity | Category | Selector | Issue |
|----------|----------|----------|-------|
${allViolations}

</details>

---
<sub>Generated by [a11y-ai](https://github.com/vudayagirivaibhav/a11y-ai) • [View full report](https://github.com/vudayagirivaibhav/a11y-ai)</sub>`;
}

function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 3) + '...';
}

function failHard(message: string): void {
  setOutput('passed', 'false');
  setOutput('fail-reason', message);
  console.error(`❌ ${message}`);
  process.exit(1);
}

function toProviderName(value: unknown): ProviderName {
  if (
    value === 'openai' ||
    value === 'anthropic' ||
    value === 'ollama' ||
    value === 'custom' ||
    value === 'mock'
  )
    return value;
  return 'custom';
}

run().catch((err) => {
  failHard(err instanceof Error ? err.message : 'GitHub Action failed');
});
